name: Publish to GHCR

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for testing
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          load: true
          push: false
          tags: test-image

      - name: Test image
        run: |
          docker run --rm test-image gcc --version
          docker run --rm test-image g++ --version
          docker run --rm test-image valgrind --version
          docker run --rm test-image cppcheck --version
          docker run --rm test-image go version

# Note that this stage is commented out for now, as the script will pull
# a new image by default and this cannot be turned off. See #17
#       - name: Test wrapper script
#         run: |
#           CAEN_REPO_NAME=test-image ./caen gcc --version
#           CAEN_REPO_NAME=test-image ./caen g++ --version
#           CAEN_REPO_NAME=test-image ./caen valgrind --version
#           CAEN_REPO_NAME=test-image ./caen cppcheck --version
#           CAEN_REPO_NAME=test-image ./caen go version

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/derickson2402/dockerized-caen
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha,prefix=sha-
          labels: |
            org.opencontainers.image.title=Dockerized-CAEN
            org.opencontainers.image.description=Containerized CAEN Linux Environment
            org.opencontainers.image.vendor=Dan Erickson (derickson2402@gmail.com)
            maintainer=Dan Erickson (derickson2402@gmail.com)

      - name: Build, tag, and push
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.labels }}
          labels: ${{ steps.meta.outputs.labels }}
