name: Test

on:
  push:
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build for testing
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          load: true
          push: false
          tags: test-image

      - name: Test image
        run: |
          docker run --rm test-image gcc --version
          docker run --rm test-image g++ --version
          docker run --rm test-image valgrind --version
          docker run --rm test-image cppcheck --version
          docker run --rm test-image go version

# Note that this stage is commented out for now, as the script will pull
# a new image by default and this cannot be turned off. See #17
#       - name: Test wrapper script
#         run: |
#           CAEN_REPO_NAME=test-image ./caen gcc --version
#           CAEN_REPO_NAME=test-image ./caen g++ --version
#           CAEN_REPO_NAME=test-image ./caen valgrind --version
#           CAEN_REPO_NAME=test-image ./caen cppcheck --version
#           CAEN_REPO_NAME=test-image ./caen go version
