name: Test

on:
  push:
  pull_request:
  release:

env:
  TEST_TAG: ghcr.io/derickson2402/dockerized-caen:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Build for testing
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          load: true
          push: false
          tags: ${{ env.TEST_TAG }}

      - name: Test image
        run: |
          docker run --rm ${{ env.TEST_TAG }} gcc --version
          docker run --rm ${{ env.TEST_TAG }} g++ --version
          docker run --rm ${{ env.TEST_TAG }} valgrind --version
          docker run --rm ${{ env.TEST_TAG }} cppcheck --version
          docker run --rm ${{ env.TEST_TAG }} go version

      - name: Test wrapper script
        run: |
          echo "$(date +%y-%m-%d)" > /tmp/caen-last-update-check
          ./caen version
          ./caen help
          ./caen gcc --version
          ./caen g++ --version
          ./caen valgrind --version
          ./caen cppcheck --version
          ./caen go version

