name: Test

on:
  push:
  pull_request:
  release:

env:
  TEST_TAG: ghcr.io/derickson2402/dockerized-caen:testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Build for testing
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          load: true
          push: false
          tags: ${{ env.TEST_TAG }}

      - name: Test image
        run: |
          docker run --rm ${{ env.TEST_TAG }} gcc --version
          docker run --rm ${{ env.TEST_TAG }} g++ --version
          docker run --rm ${{ env.TEST_TAG }} valgrind --version
          docker run --rm ${{ env.TEST_TAG }} cppcheck --version
          docker run --rm ${{ env.TEST_TAG }} go version

# Note that this stage is commented out for now, as the script will pull
# a new image by default and this cannot be turned off. See #17
#       - name: Test wrapper script
#         run: |
#           CAEN_REPO_NAME=test-image ./caen gcc --version
#           CAEN_REPO_NAME=test-image ./caen g++ --version
#           CAEN_REPO_NAME=test-image ./caen valgrind --version
#           CAEN_REPO_NAME=test-image ./caen cppcheck --version
#           CAEN_REPO_NAME=test-image ./caen go version
